name: Playwright Tests
on:
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install wait-on for server readiness check
      run: npm install -g wait-on
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Start application
      run: |
        npm run start &
        SERVER_PID=$!
        echo "SERVER_PID=$SERVER_PID" >> $GITHUB_ENV
        wait-on http://localhost:8110 --timeout 60000
      env:
        CI: true
    - name: Run Playwright tests
      run: npx playwright test
    - name: Stop application
      if: always()
      run: |
        if [ ! -z "$SERVER_PID" ]; then
          kill $SERVER_PID || true
          pkill -f "ng run for-angular-app:serve" || true
        fi
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
